/**
 * Module for filtering PR files and parsing unified diff patches.
 */

/**
 * Checks if a file should be reviewed as a valid C# file.
 */
function isReviewableCSFile(file) {
  if (!file || typeof file !== 'object') {
    return { reviewable: false, reason: 'Invalid file object' };
  }

  const filename = file.filename || '';

  // Must end in .cs (case insensitive)
  if (!filename.toLowerCase().endsWith('.cs')) {
    return { reviewable: false, reason: 'Non-C# file extension' };
  }

  // Skip deleted files
  if (file.status === 'removed') {
    return { reviewable: false, reason: 'File was deleted' };
  }

  // Skip files without patch
  if (!file.patch || typeof file.patch !== 'string' || file.patch.trim().length === 0) {
    return { reviewable: false, reason: 'Patch unavailable or empty' };
  }

  // Skip auto-generated files
  const lowerName = filename.toLowerCase();
  if (
    lowerName.endsWith('.g.cs') ||
    lowerName.endsWith('.designer.cs') ||
    lowerName.endsWith('.generated.cs') ||
    file.patch.includes('<auto-generated')
  ) {
    return { reviewable: false, reason: 'Auto-generated C# file' };
  }

  // Skip excessively large patches (> 1 MB or > 10,000 lines)
  if (file.patch.length > 1024 * 1024 || file.patch.split('\n').length > 10000) {
    return { reviewable: false, reason: 'Excessively large patch' };
  }

  return { reviewable: true };
}

/**
 * Filters PR files list to eligible C# files.
 */
function filterCSFiles(files, logger = console) {
  if (!Array.isArray(files)) return [];

  const eligible = [];
  for (const file of files) {
    const check = isReviewableCSFile(file);
    if (check.reviewable) {
      eligible.push(file);
    } else if (logger && typeof logger.info === 'function') {
      logger.info(`PR Sentry: skipped ${file.filename || 'unknown'} (${check.reason}).`);
    }
  }

  return eligible;
}

/**
 * Parses a unified diff patch and returns array of added lines with their real new-file line numbers.
 * @param {string} patch - Raw git unified diff patch text
 * @returns {Array<{ newLine: number, content: string, hunkHeader: string }>}
 */
function parsePatch(patch) {
  if (!patch || typeof patch !== 'string') {
    return [];
  }

  const lines = patch.split(/\r?\n/);
  const addedLines = [];

  let currentHunkHeader = '';
  let currentOldLine = 0;
  let currentNewLine = 0;
  let inHunk = false;

  // Regex to match header: @@ -oldStart,oldLen +newStart,newLen @@
  const hunkRegex = /^@@\s+-(\d+)(?:,(\d+))?\s+\+(\d+)(?:,(\d+))?\s+@@/;

  for (const line of lines) {
    const hunkMatch = line.match(hunkRegex);
    if (hunkMatch) {
      currentHunkHeader = line;
      currentOldLine = parseInt(hunkMatch[1], 10);
      currentNewLine = parseInt(hunkMatch[3], 10);
      inHunk = true;
      continue;
    }

    if (!inHunk) {
      continue;
    }

    if (line.startsWith('\\ No newline at end of file')) {
      continue;
    }

    if (line.startsWith('+')) {
      // Added line in new version of file
      const content = line.substring(1);
      addedLines.push({
        newLine: currentNewLine,
        content: content,
        hunkHeader: currentHunkHeader
      });
      currentNewLine++;
    } else if (line.startsWith('-')) {
      // Removed line from old version of file
      currentOldLine++;
    } else if (line.startsWith(' ') || line === '') {
      // Context line
      currentOldLine++;
      currentNewLine++;
    }
  }

  return addedLines;
}

module.exports = {
  isReviewableCSFile,
  filterCSFiles,
  parsePatch
};
